name: pDL
# name, can be override use flag -n when creating the environment
channels:
# channels refers to where Conda, the environment management tool, is going to look to find the declared dependencies
  - conda-forge
  - pytorch
  - dglteam
dependencies:
# according to channels
  - python=3.9
  - pip
  - matplotlib
  - jupyter
  - jupyterlab
  - pytorch
  - torchvision
  - torchtext
  - opencv
  - librosa
  - nb_conda_kernels
  - dgl
  - pip:
  # pip install the packages
    - torchviz